#!/usr/bin/env python3
"""Generate favicon PNGs and sync the author headshot for Prompt Anatomy."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "theme" / "promptanatomy" / "static"
AUTHOR_SOURCE_DIR = ROOT / "data" / "author"
AUTHOR_MASTER_DIR = ROOT / "data" / "01_illustrations"
AUTHOR_DEST = ROOT / "content" / "images" / "author" / "tomas-staniulis.jpg"
AUTHOR_SOURCE_NAMES = (
    "tomas-staniulis.jpg",
    "tomas-staniulis.jpeg",
    "tomas-staniulis.png",
    "tomas-staniulis.webp",
)
AUTHOR_MASTER_NAMES = ("author.jpg", "author.jpeg", "author.png", "author.webp")
AUTHOR_AVATAR_SIZE = 400

# Lockup paint from the spoke brand manual. Flat navy tile, gold bolt.
NAVY = (11, 19, 32)
GOLD = (207, 167, 58)


def _draw_bolt(draw, cx: int, cy: int, scale: float) -> None:
    """Lightning bolt matching favicon.svg geometry."""
    s = scale
    points = [
        (cx + 13.5 * s, cy + 1.5 * s),
        (cx + 4.5 * s, cy + 14.25 * s),
        (cx + 10.5 * s, cy + 14.25 * s),
        (cx + 8.25 * s, cy + 22.5 * s),
        (cx + 19.5 * s, cy + 9.75 * s),
        (cx + 13.5 * s, cy + 9.75 * s),
    ]
    draw.polygon(points, fill=GOLD)


def _icon_image(size: int):
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    # favicon.svg is rx 8 on a 32 viewBox. The in-page mark uses 12.
    radius = size * (8 / 32)
    draw.rounded_rectangle((0, 0, size - 1, size - 1), radius=radius, fill=NAVY + (255,))
    _draw_bolt(draw, int(size * 4 / 32), int(size * 3 / 32), size / 32)
    return img


def find_author_photo_source() -> Path | None:
    """Return author headshot: data/author/ names, then data/01_illustrations/author.*."""
    for name in AUTHOR_SOURCE_NAMES:
        path = AUTHOR_SOURCE_DIR / name
        if path.is_file():
            return path
    for name in AUTHOR_MASTER_NAMES:
        path = AUTHOR_MASTER_DIR / name
        if path.is_file():
            return path
    return None


def _center_crop_square(img):
    from PIL import Image

    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top = (h - side) // 2
    return img.crop((left, top, left + side, top + side))


def sync_author_photo(dest: Path = AUTHOR_DEST) -> bool:
    """Copy and resize a real headshot from data/author/. Returns True if synced."""
    src = find_author_photo_source()
    if not src:
        return False

    from PIL import Image

    dest.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as img:
        img = img.convert("RGB")
        img = _center_crop_square(img)
        img = img.resize(
            (AUTHOR_AVATAR_SIZE, AUTHOR_AVATAR_SIZE),
            Image.Resampling.LANCZOS,
        )
        img.save(dest, format="JPEG", quality=88, optimize=True)
    print(f"Synced author photo: {src.relative_to(ROOT)} -> {dest.relative_to(ROOT)}")
    return True


def sync_author_avatar(dest: Path = AUTHOR_DEST) -> None:
    """Prefer real photo from data/author/; remove stale generated placeholder when no source."""
    if sync_author_photo(dest):
        return
    if dest.is_file():
        dest.unlink()
        print(f"Removed stale avatar at {dest.relative_to(ROOT)} (was brand placeholder)")
    print("No author photo in data/author/; author bio will render without an avatar image")


def generate_favicons() -> None:
    outputs = {
        STATIC / "favicon-16x16.png": 16,
        STATIC / "favicon-32x32.png": 32,
        STATIC / "apple-touch-icon.png": 180,
        STATIC / "android-chrome-192x192.png": 192,
        STATIC / "android-chrome-512x512.png": 512,
    }
    for dest, size in outputs.items():
        _icon_image(size).save(dest, format="PNG", optimize=True)
        print(f"Wrote {dest}")


def main() -> int:
    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        print("Pillow is required. Install: pip install Pillow", file=sys.stderr)
        return 1

    # og-default.png is generated by npm run build:satori (see data/og/templates/og-default.mjs)
    generate_favicons()
    sync_author_avatar()
    return 0


if __name__ == "__main__":
    sys.exit(main())
